apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-api-deployment
  namespace: search-api
  labels:
    app: search-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: search-api
      annotations:
        kubectl.kubernetes.io/default-container: search-api
    spec:
      restartPolicy: Always
      initContainers:
        - name: wait-for-db
          image: busybox
          command:
            - sh
            - -c
            - >
              until nc -z -v -w30 search-db-service 5432; do
                echo "Waiting for db...";
                sleep 5;
              done;
      containers:
        - name: search-api
          image: wdoyle123/search-api
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          ports:
            - name: search-api
              containerPort: 8000
          livenessProbe:
            httpGet:
              path: v1/
              port: 8000
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: v1/
              port: 8000
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 10
            failureThreshold: 3
          env:
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: search-db-secret
                  key: POSTGRES_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: search-db-secret
                  key: POSTGRES_PASSWORD
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: search-db-secret
                  key: POSTGRES_DB
            - name: DATABASE_HOSTNAME
              value: "search-db-service"
            - name: DATABASE_PORT
              value: "5432"
