name: Kubernetes tooling setup
description: Installs kubectl and writes kubeconfig from a secret.

inputs:
  kubeconfig:
    description: 'The contents of KUBECONFIG file'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: latest

    - name: Configure kubeconfig
      shell: bash
      run: |
        mkdir -p ~/.kube
        echo "${{ inputs.kubeconfig }}" > ~/.kube/config
        kubectl config set current-context kubernetes-admin@kubernetes

